---
title: "SOK-1006: Arbeidskrav 6  - reworked"
author: "Daniel Fabio Groth"
title-block-banner: "darkslateblue"
format:
  html: 
    code-fold: true
    df-print: kable
output: true
editor: visual
toc: true
warning: false
---


For å gå tilbake til hovedsiden trykker du [her](https://danielfabiog.github.io/SOK-1003-og-SOK-1006/).

```{python}
import numpy as np
from matplotlib import pyplot as plt
import sympy as sp
```

**Oppgave 6**      
*I tillegg til faktorkostnaden har denne bedriften en fast kostnad på 10 000 NOK. Finn et uttrykk for total produksjonskostnad for X enheter produkt. Bruk dette uttrykket til å lage en funksjon som angir gjennomsnittskostnad (AC) på lang sikt. Tegn AC funksjonen ved å sette din funksjonen inn i koden nedenfor:*

```{python}
def kostnad_X(X):
    return (500*0.8367*X+350*1.1952*X+10000)/X
```

```{python}
x_num=np.linspace(0.001,100, 100)

fig2, ax = plt.subplots()
ax.set_ylabel('NOK', loc='top')
ax.set_xlabel('Produserte enheter', loc='right')
ax.set(xlim=(0,100))
ax.set(ylim=(0,3000))
ax.spines['top'].set_color('none')
ax.spines['right'].set_color('none')
                

# plott funksjonen her

ax.plot(x_num,kostnad_X(x_num), label='AC på lang sikt')

# tittel
ax.set_title('AC på kort og lang sikt')

#vis navnene:
ax.legend(loc='best',frameon=False);
    
```

**Oppgave 6 fortsetter**      
*I forelesning 9 har dere allerede funnet et utrykk for bedriftens totale produksjonskostnad på kort sikt som en funksjon av produsert mengde og kapitalbeholdningen: $C_s(X, K_0)=10000 + 500K_0 +\frac{350X^2}{K_0}$. Beregn den totale gjennomsnittskostnaden, og plott dette inn i figuren for $K=10, K=25, K=50$ sammen med AC på lang sikt. Brukk figuren til å forklare forholdet mellom gjennomsnittskostnaden på kort og lang sikt.*

```{python}
# Definerer funksjonen for AC på kort sikt
def funksjon(X,K):
    return (10000+500*K+(350*X**2)/K)/X

# plotter funksjonen for AC på kort sikt for K=10, 30 og 50

ax.plot(x_num, funksjon(x_num,10), label='K=10')
ax.plot(x_num, funksjon(x_num,25), label='K=25')
ax.plot(x_num, funksjon(x_num,50), label='K=50')
ax.legend(loc='best',frameon=False)
fig2
```

Forholdet mellom gjennomsnittskostnaden på kort og lang sikt er at gjennomsnittskostnaden på kort sikt er høyere enn gjennomsnittskostnaden på lang sikt. Dette skyldes at gjennomsnittskostnaden på kort sikt er en funksjon av kapitalbeholdningen, og at kapitalbeholdningen er lavere når vi produserer mindre. Dette fører til at gjennomsnittskostnaden på kort sikt er høyere enn gjennomsnittskostnaden på lang sikt.

For å gå tilbake til hovedsiden trykker du [her](https://danielfabiog.github.io/SOK-1003-og-SOK-1006/).